//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomersHospitalEntities : DbContext
    {
        public CustomersHospitalEntities()
            : base("name=CustomersHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
    
        public virtual ObjectResult<GetAllCustomersWaiting_Result> GetAllCustomersWaiting()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCustomersWaiting_Result>("GetAllCustomersWaiting");
        }
    
        public virtual int InsertCustomer(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCustomer", nameParameter);
        }
    
        public virtual ObjectResult<UpdateCustomer_Result> UpdateCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateCustomer_Result>("UpdateCustomer");
        }
    }
}
